
-- The shared init file. You'll want to fill out the info for your schema and include any other files that you need.

-- Schema info
Schema.name = "Valkyrie Networks 1936 RP"
Schema.author = "Viktor"
Schema.description = "Wholesome NRP Gaming"

ix.currency.symbol = "RM"
ix.currency.singular = "RM"
ix.currency.plural = "RMs"

-- Additional files that aren't auto-included should be included here. Note that ix.util.Include will take care of properly
-- using AddCSLuaFile, given that your files have the proper naming scheme.

-- You could technically put most of your schema code into a couple of files, but that makes your code a lot harder to manage -
-- especially once your project grows in size. The standard convention is to have your miscellaneous functions that don't belong
-- in a library reside in your cl/sh/sv_schema.lua files. Your gamemode hooks should reside in cl/sh/sv_hooks.lua. Logical
-- groupings of functions should be put into their own libraries in the libs/ folder. Everything in the libs/ folder is loaded
-- automatically.
ix.util.Include("cl_schema.lua")
ix.util.Include("sv_schema.lua")

ix.util.Include("cl_hooks.lua")
ix.util.Include("sh_hooks.lua")
ix.util.Include("sv_hooks.lua")

-- You'll need to manually include files in the meta/ folder, however.
ix.util.Include("meta/sh_character.lua")
ix.util.Include("meta/sh_player.lua")

ix.util.Include("libs/thirdparty/sh_netstream2.lua")

function Schema:ZeroNumber(number, length)
	local amount = math.max(0, length - string.len(number))
	return string.rep("0", amount)..tostring(number)
end

do
	local CLASS = {}
	CLASS.color = Color(150, 125, 175)
	CLASS.format = "%s advertises \"%s\""

	function CLASS:CanSay(speaker, text)
		if (speaker:Team() != FACTION_SERVERSTAFF) then
			speaker:NotifyLocalized("notAllowed")

			return false
		end
	end

	function CLASS:OnChatAdd(speaker, text)
		chat.AddText(self.color, string.format(self.format, speaker:Name(), text))
	end

	ix.chat.Register("advertisement", CLASS)
end

ix.anim.SetModelClass("models/brot/typhon/ss/baseline/rf6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/co1.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/co2.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/co3.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/co4.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/co5.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/co6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/en1.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/en2.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/en3.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/en4.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/en5.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/en6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/go2.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/go1.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/go3.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/go4.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/go5.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/go6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/nco1.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/nco2.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/nco3.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/nco4.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/nco5.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/nco6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/co1.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/co2.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/co3.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/co4.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/co5.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/co6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/en1.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/en2.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/en3.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/en4.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/en5.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/en6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/go2.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/go1.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/go3.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/go4.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/go5.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/go6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/nco1.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/nco2.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/nco3.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/nco4.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/nco5.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/orpo/mattishutzpolizei/nco6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/co1.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/co2.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/co3.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/co4.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/co5.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/co6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/en1.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/en2.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/en3.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/en4.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/en5.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/en6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/go2.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/go1.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/go3.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/go4.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/go5.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/go6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/nco1.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/nco2.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/nco3.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/nco4.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/nco5.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/nco6.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/reichsleitung/reichs_higher_administration_06/reichsleitung_higher_administration_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/reichsleitung/reichs_lower_administration_06/reichsleitung_lower_administration_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/reichsleitung/reichs_command_06/reichsleitung_command_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/reichsleitung/reichs_candidate_06/reichsleitung_candidate_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/gauleitung/gau_higher_administration_06/gauleitung_higher_administration_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/gauleitung/gau_lower_administration_06/gauleitung_lower_administration_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/gauleitung/gau_command_06/gauleitung_command_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/gauleitung/gau_candidate_06/gauleitung_candidate_06.mdl", "player")
ix.anim.SetModelClass("models/minson97/hitler/hitler.mdl", "player")
ix.anim.SetModelClass("models/sooth/ss/1ss/co.mdl", "player")
ix.anim.SetModelClass("models/sooth/ss/1ss/em.mdl", "player")
ix.anim.SetModelClass("models/sooth/ss/1ss/nco.mdl", "player")
ix.anim.SetModelClass("models/sooth/ss/allgemeine/co.mdl", "player")
ix.anim.SetModelClass("models/sooth/ss/allgemeine/gen.mdl", "player")
ix.anim.SetModelClass("models/sooth/ss/sd/co.mdl", "player")
ix.anim.SetModelClass("models/sooth/ss/sd/nco.mdl", "player")
ix.anim.SetModelClass("models/sooth/ss/stapo/nco.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/ordnungspolizei/schutzpolizei/co/schutzpolizei_officer.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/ordnungspolizei/schutzpolizei/en/schutzpolizei_enlisted.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/ordnungspolizei/schutzpolizei/gen/schutzpolizei_general.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/ordnungspolizei/schutzpolizei/snco/schutzpolizei_senior-nco.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/gauleitung/gau_candidate_06/gauleitung_candidate_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/gauleitung/gau_command_06/gauleitung_command_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/gauleitung/gau_command_summer_06/gauleitung_command_summer_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/gauleitung/gau_higher_administration_06/gauleitung_higher_administration_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/gauleitung/gau_higher_administration_summer_06/gauleitung_higher_administration_summer_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/gauleitung/gau_lower_administration_06/gauleitung_lower_administration_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/gauleitung/gau_lower_administration_summer_06/gauleitung_lower_administration_summer_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/reichsleitung/reichs_candidate_06/reichsleitung_candidate_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/reichsleitung/reichs_command_06/reichsleitung_command_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/reichsleitung/reichs_command_summer_06/reichsleitung_command_summer_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/reichsleitung/reichs_higher_administration_06/reichsleitung_higher_administration_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/reichsleitung/reichs_higher_administration_summer_06/reichsleitung_higher_administration_summer_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/reichsleitung/reichs_lower_administration_06/reichsleitung_lower_administration_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/matti/pm0v3/nsdap/reichsleitung/reichs_lower_administration_summer_06/reichsleitung_lower_administration_summer_06.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/hilter.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/rf4.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40_s1_01.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40_s1_02.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40_s1_03.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40_s1_04.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40_s1_05.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40_s1_06.md", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/nco/m40_s1_01.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/nco/m40_s1_02.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/nco/m40_s1_03.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/nco/m40_s1_04.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/nco/m40_s1_05.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/nco/m40_s1_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/co/m38_s1_01.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/co/m38_s1_02.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/co/m38_s1_03.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/co/m38_s1_04.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/co/m38_s1_05.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/co/m38_s1_06.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/1stssvt/co6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/1stssvt/en6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/1stssvt/go6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/1stssvt/nco6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/co6.mdl", "player")
ix.anim.SetModelClass("mmodels/brot/typhon/ss/baseline/en6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/go6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/baseline/nco6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/feld/co6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/feld/en6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/feld/go6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/feld/nco6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/co6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/en6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/go6.mdl", "player")
ix.anim.SetModelClass("models/brot/typhon/ss/sd/nco6.mdl", "player")
ix.anim.SetModelClass("models/princeminusa/suits/male_09_closed_tie.mdl", "player")
ix.anim.SetModelClass("models/princeminusa/suits/male_04_closed_tie.mdl", "player")
ix.anim.SetModelClass("models/princeminusa/suits/male_08_closed_tie.mdl", "player")
ix.anim.SetModelClass("models/princeminusa/suits/male_07_closed_tie.mdl", "player")
ix.anim.SetModelClass("models/princeminusa/suits/male_06_closed_tie.mdl", "player")
ix.anim.SetModelClass("models/princeminusa/suits/male_02_closed_tie.mdl", "player")
ix.anim.SetModelClass("models/princeminusa/suits/male_10_closed_tie.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40_s1_01.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40_s1_02.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40_s1_03.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40_s1_04.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40_s1_05.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40_s1_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/nco/m40c_s1_01.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/nco/m40c_s1_02.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/nco/m40c_s1_03.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/nco/m40c_s1_04.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/nco/m40c_s1_05.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/nco/m40c_s1_06.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40c_s1_01.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40c_s1_02.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40c_s1_03.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40c_s1_04.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40c_s1_05.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/gd_heer/infantry/en/m40c_s1_06.mdl", "player")
ix.anim.SetModelClass("models/sooth/ss/stapo/co.mdl", "player")
ix.anim.SetModelClass("models/hts/comradebear/pm0v3/ordnungspolizei/schutzpolizei/nco/schutzpolizei_nco.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_04_closed_coat_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_04_open_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_04_closed_coat_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_04_closed_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_04_open.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_04_open_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_04_open_waistcoat.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_04_shirt.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_04_shirt_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_09_closed_coat_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_09_closed_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_09_open.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_09_open_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_09_open_waistcoat.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_09_shirt.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_09_shirt_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_06_closed_coat_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_06_closed_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_06_open.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_06_open_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_06_open_waistcoat.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_06_shirt.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_06_shirt_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_08_closed_coat_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_08_closed_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_02_open_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_02_open_waistcoat.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_02_shirt.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_02_shirt_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_07_closed_coat_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_07_closed_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_07_open.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_07_open_tie.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_07_open_waistcoat.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_07_shirt.mdl", "player")
ix.anim.SetModelClass("models/player/suits/male_07_shirt_tie.mdl", "player")
ix.anim.SetModelClass("models/frock/admirals/admiralfrock02.mdl", "player")
ix.anim.SetModelClass("models/frock/admirals/admiralfrock01.mdl", "player")
ix.anim.SetModelClass("models/frock/admirals/admiralfrock03.mdl", "player")
ix.anim.SetModelClass("models/frock/admirals/admiralfrock04.mdl", "player")
ix.anim.SetModelClass("models/frock/admirals/admiralfrock05.mdl", "player")
ix.anim.SetModelClass("models/frock/admirals/admiralfrock06.mdl", "player")
ix.anim.SetModelClass("models/frock/admirals/strassefrock.mdl", "player")
ix.anim.SetModelClass("models/frock/juniorofficers/juniorofficerfrock01.mdl", "player")
ix.anim.SetModelClass("models/frock/juniorofficers/juniorofficerfrock02.mdl", "player")
ix.anim.SetModelClass("models/frock/juniorofficers/juniorofficerfrock03.mdl", "player")
ix.anim.SetModelClass("models/frock/juniorofficers/juniorofficerfrock04.mdl", "player")
ix.anim.SetModelClass("models/frock/juniorofficers/juniorofficerfrock05.mdl", "player")
ix.anim.SetModelClass("models/frock/juniorofficers/juniorofficerfrock06.mdl", "player")
ix.anim.SetModelClass("models/frock/seniorofficers/seniorofficerfrock01.mdl", "player")
ix.anim.SetModelClass("models/frock/seniorofficers/seniorofficerfrock02.mdl", "player")
ix.anim.SetModelClass("models/frock/seniorofficers/seniorofficerfrock03.mdl", "player")
ix.anim.SetModelClass("models/frock/seniorofficers/seniorofficerfrock04.mdl", "player")
ix.anim.SetModelClass("models/frock/seniorofficers/seniorofficerfrock05.mdl", "player")
ix.anim.SetModelClass("models/frock/seniorofficers/seniorofficerfrock06.mdl", "player")
ix.anim.SetModelClass("models/marines/chief/chiefmarine01.mdl", "player")
ix.anim.SetModelClass("models/marines/chief/chiefmarine02.mdl", "player")
ix.anim.SetModelClass("models/marines/chief/chiefmarine03.mdl", "player")
ix.anim.SetModelClass("models/marines/chief/chiefmarine04.mdl", "player")
ix.anim.SetModelClass("models/marines/chief/chiefmarine05.mdl", "player")
ix.anim.SetModelClass("models/marines/chief/chiefmarine06.mdl", "player")
ix.anim.SetModelClass("models/marines/juniorofficers/juniorofficermarine01.mdl", "player")
ix.anim.SetModelClass("models/marines/juniorofficers/juniorofficermarine02.mdl", "player")
ix.anim.SetModelClass("models/marines/juniorofficers/juniorofficermarine03.mdl", "player")
ix.anim.SetModelClass("models/marines/juniorofficers/juniorofficermarine04.mdl", "player")
ix.anim.SetModelClass("models/marines/juniorofficers/juniorofficermarine05.mdl", "player")
ix.anim.SetModelClass("models/marines/juniorofficers/juniorofficermarine06.mdl", "player")
ix.anim.SetModelClass("models/marines/po/pomarine01.mdl", "player")
ix.anim.SetModelClass("models/marines/po/pomarine02.mdl", "player")
ix.anim.SetModelClass("models/marines/po/pomarine03.mdl", "player")
ix.anim.SetModelClass("models/marines/po/pomarine04.mdl", "player")
ix.anim.SetModelClass("models/marines/po/pomarine05.mdl", "player")
ix.anim.SetModelClass("models/marines/po/pomarine06.mdl", "player")
ix.anim.SetModelClass("models/marines/sailor/marine01.mdl", "player")
ix.anim.SetModelClass("models/marines/sailor/marine02.mdl", "player")
ix.anim.SetModelClass("models/marines/sailor/marine03.mdl", "player")
ix.anim.SetModelClass("models/marines/sailor/marine04.mdl", "player")
ix.anim.SetModelClass("models/marines/sailor/marine05.mdl", "player")
ix.anim.SetModelClass("models/marines/sailor/marine06.mdl", "player")
ix.anim.SetModelClass("models/marines/seniorofficers/seniorofficermarine01.mdl", "player")
ix.anim.SetModelClass("models/marines/seniorofficers/seniorofficermarine02.mdl", "player")
ix.anim.SetModelClass("models/marines/seniorofficers/seniorofficermarine03.mdl", "player")
ix.anim.SetModelClass("models/marines/seniorofficers/seniorofficermarine04.mdl", "player")
ix.anim.SetModelClass("models/marines/seniorofficers/seniorofficermarine05.mdl", "player")
ix.anim.SetModelClass("models/marines/seniorofficers/seniorofficermarine06.mdl", "player")
ix.anim.SetModelClass("models/seaservice/admirals/admiralsea01.mdl", "player")
ix.anim.SetModelClass("models/seaservice/admirals/admiralsea02.mdl", "player")
ix.anim.SetModelClass("models/seaservice/admirals/admiralsea03.mdl", "player")
ix.anim.SetModelClass("models/seaservice/admirals/admiralsea04.mdl", "player")
ix.anim.SetModelClass("models/seaservice/admirals/admiralsea05.mdl", "player")
ix.anim.SetModelClass("models/seaservice/admirals/admiralsea06.mdl", "player")
ix.anim.SetModelClass("models/seaservice/admirals/strassesea.mdl", "player")
ix.anim.SetModelClass("models/seaservice/chief/chiefsea01.mdl", "player")
ix.anim.SetModelClass("models/seaservice/chief/chiefsea01.mdl", "player")
ix.anim.SetModelClass("models/seaservice/chief/chiefsea02.mdl", "player")
ix.anim.SetModelClass("models/seaservice/chief/chiefsea03.mdl", "player")
ix.anim.SetModelClass("models/seaservice/chief/chiefsea04.mdl", "player")
ix.anim.SetModelClass("models/seaservice/chief/chiefsea05.mdl", "player")
ix.anim.SetModelClass("models/seaservice/chief/chiefsea06.mdl", "player")
ix.anim.SetModelClass("models/seaservice/juniorofficers/juniorofficersea01.mdl", "player")
ix.anim.SetModelClass("models/seaservice/juniorofficers/juniorofficersea02.mdl", "player")
ix.anim.SetModelClass("models/seaservice/juniorofficers/juniorofficersea03.mdl", "player")
ix.anim.SetModelClass("models/seaservice/juniorofficers/juniorofficersea04.mdl", "player")
ix.anim.SetModelClass("models/seaservice/juniorofficers/juniorofficersea05.mdl", "player")
ix.anim.SetModelClass("models/seaservice/juniorofficers/juniorofficersea06.mdl", "player")
ix.anim.SetModelClass("models/seaservice/midshipman/midshipman01.mdl", "player")
ix.anim.SetModelClass("models/seaservice/midshipman/midshipman02.mdl", "player")
ix.anim.SetModelClass("models/seaservice/midshipman/midshipman03.mdl", "player")
ix.anim.SetModelClass("models/seaservice/midshipman/midshipman04.mdl", "player")
ix.anim.SetModelClass("models/seaservice/midshipman/midshipman05.mdl", "player")
ix.anim.SetModelClass("models/seaservice/midshipman/midshipman06.mdl", "player")
ix.anim.SetModelClass("models/seaservice/po/posea01.mdl", "player")
ix.anim.SetModelClass("models/seaservice/po/posea02.mdl", "player")
ix.anim.SetModelClass("models/seaservice/po/posea03.mdl", "player")
ix.anim.SetModelClass("models/seaservice/po/posea04.mdl", "player")
ix.anim.SetModelClass("models/seaservice/po/posea05.mdl", "player")
ix.anim.SetModelClass("models/seaservice/po/posea06.mdl", "player")
ix.anim.SetModelClass("models/seaservice/sailor/sailor01.mdl", "player")
ix.anim.SetModelClass("models/seaservice/sailor/sailor02.mdl", "player")
ix.anim.SetModelClass("models/seaservice/sailor/sailor03.mdl", "player")
ix.anim.SetModelClass("models/seaservice/sailor/sailor04.mdl", "player")
ix.anim.SetModelClass("models/seaservice/sailor/sailor05.mdl", "player")
ix.anim.SetModelClass("models/seaservice/sailor/sailor06.mdl", "player")
ix.anim.SetModelClass("models/seaservice/seniorofficers/seniorofficersea01.mdl", "player")
ix.anim.SetModelClass("models/seaservice/seniorofficers/seniorofficersea02.mdl", "player")
ix.anim.SetModelClass("models/seaservice/seniorofficers/seniorofficersea03.mdl", "player")
ix.anim.SetModelClass("models/seaservice/seniorofficers/seniorofficersea04.mdl", "player")
ix.anim.SetModelClass("models/seaservice/seniorofficers/seniorofficersea05.mdl", "player")
ix.anim.SetModelClass("models/seaservice/seniorofficers/seniorofficersea06.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_rf.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_03_rf.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_co.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_en.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_gen.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_gerich_nco.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_gericht_co.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_gericht_en.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_gericht_gen.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_lss_co.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_lss_en.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_nco.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_lss_nco.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_nco.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_rsha_co.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_rsha_en.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_rsha_gen.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_06_rsha_nco.mdl", "player")
ix.anim.SetModelClass("models/ss/ss_amon_allemand.mdl", "player")
ix.anim.SetModelClass("models/schl/luftwaffe/nco.mdl", "player")
ix.anim.SetModelClass("models/schl/luftwaffe/gen.mdl", "player")
ix.anim.SetModelClass("models/schl/luftwaffe/co.mdl", "player")
ix.anim.SetModelClass("models/schl/luftwaffe/em.mdl", "player")